// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbtywvxwgslaxagfkdcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJidHl3dnh3Z3NsYXhhZ2ZrZGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MzAzNjcsImV4cCI6MjA2OTMwNjM2N30.IIQEXLdk0PwdRDhRfgwROBMU78lqXIQr7_NDuLllDq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});